spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/steepsalvadorman/microservice-config-data.git
          clone-on-start: true
          default-label: main
          username: ${GITHUB_USER}
          password: ${GITHUB_TOKEN}
server:
  port: 8888